name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-22.04-arm
    
    steps:
      - uses: actions/checkout@v4
      - uses: aptos-labs/aptos-core/.github/actions/rust-setup@main
      - name: Build
        run: RUSTFLAGS="--cfg tokio_unstable" cargo build -r
